"""initial schema all pairs

Revision ID: 19bea6c2f9a4
Revises: 
Create Date: 2026-09-05 14:20:14.500108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19bea6c2f9a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_milestone',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('application_ref', sa.String(length=64), nullable=False),
    sa.Column('district_code', sa.String(length=8), nullable=False),
    sa.Column('scheme_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('reported_by', sa.String(length=16), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('state_code', sa.String(length=8), nullable=False),
    sa.Column('district_code', sa.String(length=8), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_template',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.Column('label_local', sa.JSON(), nullable=False),
    sa.Column('capex_items', sa.JSON(), nullable=False),
    sa.Column('monthly_opex', sa.JSON(), nullable=False),
    sa.Column('monthly_revenue_estimate', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheme',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('corporation', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_body', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_version',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scheme_id', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_authority', sa.String(length=32), nullable=False),
    sa.Column('extracted_by', sa.String(length=48), nullable=False),
    sa.Column('extraction_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_human', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['source_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_version')
    op.drop_table('source_snapshot')
    op.drop_table('scheme')
    op.drop_table('cost_template')
    op.drop_table('channel')
    op.drop_table('application_milestone')
    # ### end Alembic commands ###
